name: Bug Report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.5 / Windows 11"
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Launch app  2. Do X  3. See error"
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Logs
